#!/usr/bin/env node
// tools/gen_public_suffix.js — build lib/_public_suffix.js from a local copy of
// the Public Suffix List (https://publicsuffix.org/list/public_suffix_list.dat).
//
//   node tools/gen_public_suffix.js <path to public_suffix_list.dat> [out]
//
// Reads a FILE; never fetches. Keeps the ICANN section only (the private
// section names hosting platforms, whose customers are not the mail-domain
// owners this key is about), and of it only:
//   - rules of two or more labels (co.uk, ac.jp, ...),
//   - every wildcard rule (*.ck) and every exception rule (!www.ck).
// Single-label rules (com, uk, pw) are dropped: the algorithm's default rule
// "*" already makes any TLD a public suffix, so they add nothing.
// Unicode rules are converted to their ASCII (punycode) form, the form a mail
// domain reaches us in. Output is one sorted array, one rule per line.
"use strict";

const fs = require("fs");
const path = require("path");
const url = require("url");

function parse(text) {
  const lines = text.split(/\r?\n/);
  let version = null;
  let commit = null;
  let inIcann = false;
  const rules = new Set();
  for (const raw of lines) {
    const line = raw.trim();
    const v = /^\/\/ VERSION: (\S+)/.exec(line);
    if (v) version = v[1];
    const c = /^\/\/ COMMIT: (\S+)/.exec(line);
    if (c) commit = c[1];
    if (line === "// ===BEGIN ICANN DOMAINS===") { inIcann = true; continue; }
    if (line === "// ===END ICANN DOMAINS===") { inIcann = false; continue; }
    if (!inIcann || !line || line.startsWith("//")) continue;
    const rule = line.split(/\s/)[0];
    let prefix = "";
    let body = rule;
    if (body.startsWith("!")) { prefix = "!"; body = body.slice(1); }
    const labels = body.split(".").map((l) => (l === "*" ? "*" : url.domainToASCII(l) || null));
    if (labels.some((l) => !l)) throw new Error(`cannot convert rule to ASCII: ${rule}`);
    const ascii = prefix + labels.join(".");
    const special = prefix === "!" || labels.includes("*");
    if (special || labels.length >= 2) rules.add(ascii);
  }
  if (!rules.size) throw new Error("no ICANN rules found: is this the Public Suffix List?");
  return { version, commit, rules: [...rules].sort() };
}

// Several rules per line, lines at most 100 columns: compact, still diffable.
function packRows(rules) {
  const rows = [];
  let row = " ";
  for (const r of rules) {
    const item = ` ${JSON.stringify(r)},`;
    if (row.length + item.length > 100) { rows.push(row); row = " "; }
    row += item;
  }
  if (row.trim()) rows.push(row);
  return rows.join("\n");
}

function render({ version, commit, rules }, sourceName) {
  return (
    "// lib/_public_suffix.js — GENERATED by tools/gen_public_suffix.js; do not edit by hand.\n" +
    `// Source: the Public Suffix List (https://publicsuffix.org/list/), file ${sourceName},\n` +
    `// VERSION ${version || "unknown"}, COMMIT ${commit || "unknown"}. ICANN section only:\n` +
    "// rules of two or more labels plus every wildcard and exception rule (single-label\n" +
    "// rules are implied by the default rule \"*\"). Regenerate:\n" +
    "//   node tools/gen_public_suffix.js <path to public_suffix_list.dat>\n" +
    "// The list is licensed MPL-2.0 (https://mozilla.org/MPL/2.0/).\n" +
    "\"use strict\";\n\n" +
    `const PSL_VERSION = ${JSON.stringify(version)};\n` +
    `const PSL_COMMIT = ${JSON.stringify(commit)};\n` +
    "const RULES = [\n" +
    packRows(rules) +
    "\n];\n\n" +
    "const NORMAL = new Set();\n" +
    "const WILDCARD = new Set(); // stored without the leading \"*.\"\n" +
    "const EXCEPTION = new Set(); // stored without the leading \"!\"\n" +
    "for (const r of RULES) {\n" +
    "  if (r.startsWith(\"!\")) EXCEPTION.add(r.slice(1));\n" +
    "  else if (r.startsWith(\"*.\")) WILDCARD.add(r.slice(2));\n" +
    "  else NORMAL.add(r);\n" +
    "}\n\n" +
    "// publicSuffix(host) -> the public suffix under the standard algorithm\n" +
    "// (https://github.com/publicsuffix/list/wiki/Format#formal-algorithm):\n" +
    "// an exception rule wins and its suffix is the rule minus its leftmost label;\n" +
    "// otherwise the matching rule with the most labels; otherwise the default\n" +
    "// rule \"*\" (the last label).\n" +
    "function publicSuffix(host) {\n" +
    "  const labels = String(host || \"\").toLowerCase().replace(/\\.$/, \"\").split(\".\").filter(Boolean);\n" +
    "  if (!labels.length) return \"\";\n" +
    "  for (let i = 0; i < labels.length; i++) {\n" +
    "    const s = labels.slice(i).join(\".\");\n" +
    "    if (EXCEPTION.has(s)) return labels.slice(i + 1).join(\".\");\n" +
    "  }\n" +
    "  // Walk from the longest candidate down: the first hit has the most labels.\n" +
    "  for (let i = 0; i < labels.length; i++) {\n" +
    "    const s = labels.slice(i).join(\".\");\n" +
    "    if (NORMAL.has(s)) return s;\n" +
    "    if (i + 1 < labels.length && WILDCARD.has(labels.slice(i + 1).join(\".\"))) return s;\n" +
    "  }\n" +
    "  return labels[labels.length - 1];\n" +
    "}\n\n" +
    "// registrableDomain(host) -> the public suffix plus one label. A host that\n" +
    "// IS a public suffix (nothing left of it) is returned whole.\n" +
    "function registrableDomain(host) {\n" +
    "  const labels = String(host || \"\").toLowerCase().replace(/\\.$/, \"\").split(\".\").filter(Boolean);\n" +
    "  const ps = publicSuffix(labels.join(\".\"));\n" +
    "  const n = ps ? ps.split(\".\").length : 0;\n" +
    "  if (labels.length <= n) return labels.join(\".\");\n" +
    "  return labels.slice(-(n + 1)).join(\".\");\n" +
    "}\n\n" +
    "module.exports = { PSL_VERSION, PSL_COMMIT, RULES, publicSuffix, registrableDomain };\n"
  );
}

function main() {
  const input = process.argv[2];
  if (!input) {
    console.error("usage: node tools/gen_public_suffix.js <path to public_suffix_list.dat> [out]");
    process.exit(2);
  }
  const out = process.argv[3] || path.join(__dirname, "..", "lib", "_public_suffix.js");
  const parsed = parse(fs.readFileSync(input, "utf8"));
  fs.writeFileSync(out, render(parsed, "public_suffix_list.dat"));
  console.log(`wrote ${out}: ${parsed.rules.length} rules, VERSION ${parsed.version}, COMMIT ${parsed.commit}`);
}

if (require.main === module) main();

module.exports = { parse, render };
